# Generated by Django 4.1.3 on 2022-12-02 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('fechaNacimiento', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='desafioMVT.persona')),
            ],
            bases=('desafioMVT.persona',),
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='desafioMVT.persona')),
            ],
            bases=('desafioMVT.persona',),
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='desafioMVT.persona')),
                ('oficio', models.CharField(max_length=250)),
            ],
            bases=('desafioMVT.persona',),
        ),
    ]
