# Generated by Django 4.1.3 on 2022-12-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafioMVT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='gradoEscolar',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
