# Generated by Django 4.1.3 on 2022-12-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafioMVT', '0002_hermano_gradoescolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='amamanta',
            field=models.BooleanField(default=False),
        ),
    ]
