# Generated by Django 4.1.3 on 2022-12-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafioMVT', '0003_madre_amamanta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Apellido',
            new_name='apellido',
        ),
    ]
