# Generated by Django 4.1.3 on 2022-12-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafioMVT', '0004_rename_apellido_persona_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madre',
            name='persona_ptr',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='persona_ptr',
        ),
        migrations.AddField(
            model_name='persona',
            name='rolFamiliar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Hermano',
        ),
        migrations.DeleteModel(
            name='Madre',
        ),
        migrations.DeleteModel(
            name='Padre',
        ),
    ]
